app/src/main/java/app/revanced/manager/ui/models/DashboardViewModel.kt

Yeah, 1 less TODO to  do. 9 remaining.

feat: add manager github commit checker back

---

lib/ui/views/home/home_view.dart

- added PageTransitionSwitcher to HomeView
https://user-images.githubusercontent.com/55922348/190903323-412c5bb2-305a-4b55-ba74-52025e04379a.mov

feat: animate switching updates on HomeView

---

lib/ui/views/navigation/navigation_viewmodel.dart
lib/ui/views/settings/settings_viewmodel.dart

fix: navigation bar color

---

assets/i18n/en.json
lib/ui/views/app_selector/app_selector_view.dart
lib/ui/views/patches_selector/patches_selector_view.dart
lib/ui/widgets/appSelectorView/app_skeleton_loader.dart

feat: CustomScrollView in app and patches selector views

---

lib/ui/views/patches_selector/patches_selector_viewmodel.dart

feat: allow searching for displayed patch names

---

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt

- Remove gimmicky logging which involves printing `[` and `]`.
- Increase consistency in logging errors

feat: simplify logging

---

.github/workflows/debug-build.yml
.github/workflows/release-build.yml
.gitignore
android/app/build.gradle
lib/main.dart
lib/utils/environment.dart

Switches to using GitHub secrets for API keys and re-enables sentry.

feat: use secrets for keys

---

README.md

Fixed link to documentation that was no longer was accurate

docs: update broken link in Readme

---

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
lib/models/patch.dart
lib/services/patcher_api.dart
lib/ui/views/patches_selector/patches_selector_viewmodel.dart

Fixes https://github.com/revanced/revanced-manager/issues/576

feat: add support for shared patches

---

.github/workflows/commit-build.yml
.github/workflows/crowdin.yml
.github/workflows/pull-request-build.yml

- Bump upload-artifact to v3
- Update crowdin/github-action according to new versioning format https://github.com/crowdin/github-action/releases/tag/v1.6.0

Update workflow actions

---

lib/ui/views/home/home_viewmodel.dart

Futher testing is needed to confirm if this fix solves is or not.

fix: potentially fix apps disappearing when update is available.

---

lib/ui/widgets/patchesSelectorView/patch_item.dart

Increased max lines in the description to 4

fix: Long patch description truncated

---

.vscode/settings.json
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

chore: bump gradle 7.5-rc.1 -> 7.6.1

chore: bump gradle 7.5-rc.1 -> 7.6.1

---

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt

chore: `addFiles` -> `addIntegrations`
> This was prompted by the release of 7.0.0 https://github.com/revanced/revanced-patcher/releases/tag/v7.0.0
fix: #721

chore: `addFiles` -> `addIntegrations`

---

analysis_options.yaml
lib/app/app.dart
lib/main.dart
lib/services/crowdin_api.dart
lib/services/github_api.dart
lib/services/manager_api.dart
lib/services/patcher_api.dart
lib/services/revanced_api.dart
lib/services/root_api.dart
lib/ui/views/app_selector/app_selector_viewmodel.dart
lib/ui/views/home/home_viewmodel.dart
lib/ui/views/installer/installer_viewmodel.dart
lib/ui/views/navigation/navigation_viewmodel.dart
lib/ui/views/settings/settingsFragment/settings_update_language.dart
lib/ui/views/settings/settings_viewmodel.dart

🧹 chore: ignore `gradle.properties`
Ignore `gradle.properties`, this is to prevent accidental leaks...
Hey, this PR also test the new `Android CI PR Build` action!

chore: ignore `gradle.properties`

---

assets/i18n/en_US.json
lib/services/manager_api.dart
lib/ui/views/home/home_view.dart
lib/ui/views/home/home_viewmodel.dart
lib/ui/widgets/homeView/latest_commit_card.dart

To be documented (has no effect on PR status)
<details>
<summary>Preview</summary>
</details>

feat: update patches button

---

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
assets/i18n/en_US.json
lib/services/manager_api.dart
lib/services/patcher_api.dart
lib/ui/views/settings/settingsFragment/settings_manage_keystore_password.dart
lib/ui/views/settings/settings_viewmodel.dart
lib/ui/widgets/settingsView/settings_advanced_section.dart
lib/ui/widgets/settingsView/settings_export_section.dart

add option to import/export keystore used to sign apks

feat: add option to import/export keystore

---

lib/ui/views/settings/settingsFragment/settings_manage_sources.dart

Dismiss the source (not reset source) pop-up when resetting source
Pop pop!
https://user-images.githubusercontent.com/93124920/233429349-1cec6ecd-2726-4d8b-b274-b639b9f98ce6.mp4

feat: resetting source to default dismiss the sources pop-up

---

.gitignore
analysis_options.yaml
android/build.gradle
lib/services/github_api.dart
lib/services/revanced_api.dart
lib/ui/views/app_selector/app_selector_view.dart
lib/ui/views/patches_selector/patches_selector_view.dart
lib/ui/widgets/homeView/latest_commit_card.dart
lib/ui/widgets/settingsView/social_media_widget.dart
pubspec.yaml

This PR updates minimum dart version to 3.0.0.

build: migrate to dart 3

---

android/app/build.gradle

chore(deps): bump `revanced-patcher` to `8.0.0`

---

pubspec.yaml

You forgot to update pubspec.yaml file with the latest release.

build: bump version to 1.3.0

---

docs/0_prerequisites.md
docs/1_installation.md
docs/2_1_patching.md
docs/2_2_managing.md
docs/2_3_updating.md
docs/2_4_settings.md
docs/2_usage.md
docs/3_troubleshooting.md
docs/4_building.md
docs/README.md

Supersedes https://github.com/revanced/revanced-manager/pull/706.
The style is oriented on https://github.com/revanced/revanced-cli/tree/main/docs

docs: init

---

docs/3_troubleshooting.md

_No description provided._
<br>
> * Changelog came from commit description
<br>
`docs`: 84a91682b31209c31574a0d325920077d0448943 - Self-explanatory - Fix markdown styling issue

docs(troubleshooting): fix markdown styling

---

assets/i18n/en_US.json
lib/ui/views/app_selector/app_selector_view.dart
lib/ui/widgets/appSelectorView/installed_app_item.dart
lib/ui/widgets/appSelectorView/not_installed_app_item.dart

feat: clarify suggested version in app list

---

lib/services/patcher_api.dart
lib/services/root_api.dart

feat: Use `/data/adb/revanced` again and ensure migration scenario

---

assets/i18n/en_US.json
lib/ui/views/patcher/patcher_viewmodel.dart

fix: different message when trying to patch spilt apk

---

lib/ui/views/app_selector/app_selector_view.dart
lib/ui/views/app_selector/app_selector_viewmodel.dart

fix: patchable apps not showing if none of them is installed

---

lib/ui/widgets/homeView/installed_apps_card.dart

fix(patched-applications): non-patched app showing on `Installed` section

---

lib/ui/widgets/homeView/installed_apps_card.dart

fix: patched applications not showing at launch

---

.github/workflows/analyze.yml
android/app/src/main/AndroidManifest.xml
android/gradle.properties
fastlane/metadata/android/en-US/short_description.txt
lib/ui/views/settings/settingsFragment/settings_manage_api_url.dart
lib/ui/widgets/homeView/installed_apps_card.dart
pubspec.yaml

Before merge
Team note: you can take control of release by... mark the PR as ready or edit this PR
--------------------
8 Commits (2+3+1+1+1)
* 🐛 2 Bug Fixes 
* 🤖 3 CI/CD Changes 
* ⚙️ 1 Build Change 
* 📝 1 Documentation Improvement 
* 🧹 1 Miscellaneous Change 
--------------------
ReVanced Manager (Next)

chore: merge `dev` branch to `main` branch

---

lib/ui/widgets/settingsView/settings_export_section.dart

fix: keystore password dialog showing up before importing

---

assets/i18n/en_US.json
lib/ui/views/patches_selector/patches_selector_view.dart
lib/ui/views/patches_selector/patches_selector_viewmodel.dart

https://github.com/ReVanced/revanced-manager/assets/39409020/1ccda832-910a-4016-a6b6-09b461c38374

fix(patches-selector): separate all universal patches to the bottom

---

assets/i18n/en_US.json
lib/services/manager_api.dart
lib/ui/views/installer/installer_viewmodel.dart
lib/ui/views/patches_selector/patches_selector_view.dart
lib/ui/views/patches_selector/patches_selector_viewmodel.dart
lib/ui/widgets/patchesSelectorView/patch_item.dart

feat(patches-selector): show `New` tag for new patches

---

assets/i18n/en_US.json
lib/services/manager_api.dart
lib/ui/views/installer/installer_viewmodel.dart
lib/ui/views/patcher/patcher_view.dart
lib/ui/views/patcher/patcher_viewmodel.dart

feat(patcher-view): show notice for removed patches used previously

---

lib/ui/views/app_selector/app_selector_view.dart
lib/ui/views/contributors/contributors_view.dart
lib/ui/views/installer/installer_view.dart
lib/ui/views/navigation/navigation_viewmodel.dart
lib/ui/views/patches_selector/patches_selector_view.dart
lib/ui/widgets/appSelectorView/app_skeleton_loader.dart
lib/ui/widgets/installerView/gradient_progress_indicator.dart
lib/ui/widgets/patchesSelectorView/patch_options_fields.dart

- It will enhance performance and minimise rebuild whenever any `MediaQuery` properties are modified.

refactor: migrate MediaQuery properties to InheritedModel

---

docs/1_installation.md
docs/2_1_patching.md
docs/2_2_managing.md
docs/2_3_updating.md
docs/2_4_settings.md
docs/2_usage.md
docs/3_troubleshooting.md
docs/README.md

improved overall docs appearance

docs(fixed): replaced some emoji icons, not rendering on chromium based browsers on windows

---

.github/ISSUE_TEMPLATE/bug-issue.yml
.github/ISSUE_TEMPLATE/feature-issue.yml

This PR simplifies both issue templates by reducing the amount of required fields and fixing some language mistakes.

chore: simplify issue templates

---

.github/workflows/pr-build.yml

This implement the suggested solution in #1230 
----------------------------------------------------
[![SDBSuggested](https://github.com/ReVanced/revanced-manager/assets/93124920/33b53a11-63b4-4b57-b1b5-76de92890573)](#1230)

ci(pr-build): sign debug apk

---

README.md

closes https://github.com/ReVanced/revanced-manager/issues/962

docs(readme): add documentation and minor fixes

---

lib/ui/widgets/settingsView/social_media_widget.dart

Updated from https://youtube.com/revanced to https://youtube.com/@revanced

fix: update youtube link

---

lib/ui/views/installer/installer_viewmodel.dart

Updates the padding of the install type dialog as mentioned in #1279

fix(install-type): update padding and enable radio list scrolling

---

app/src/main/java/app/revanced/manager/ui/screen/settings/AboutSettingsScreen.kt

The submit issue button now takes you to: https://github.com/ReVanced/revanced-manager/issues/new/choose

feat: implement Submit Issue button

---

lib/ui/views/app_selector/app_selector_view.dart
lib/ui/views/patches_selector/patches_selector_view.dart

Manager was complaining that the search bar was overflowing by 2 pixels

fix: search bar overflow

---

app/src/main/res/values/strings.xml

fix: Updates popup shows incorrect names

---

android/app/build.gradle
android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
lib/services/patcher_api.dart
lib/ui/views/installer/installer_viewmodel.dart

Fix the issue with reloading patches after patching.

perf: Do not load patches twice

---

lib/ui/views/app_selector/app_selector_viewmodel.dart

fix: search with package name

---

lib/ui/views/app_selector/app_selector_view.dart
lib/ui/views/patches_selector/patches_selector_view.dart

| Before | After |
|----|-----|

fix(app-bar): title not hiding completely

---

lib/ui/views/navigation/navigation_viewmodel.dart

feat: Remove full external storage access

---

lib/app/app.dart
lib/main.dart
lib/services/download_manager.dart
lib/services/github_api.dart
lib/services/revanced_api.dart
lib/ui/widgets/contributorsView/contributors_card.dart

Adds a user agent to all outgoing requests
closes: #1359

feat: add user agent

---

assets/i18n/en_US.json
lib/services/manager_api.dart
lib/ui/views/patcher/patcher_viewmodel.dart
lib/ui/views/patches_selector/patches_selector_viewmodel.dart
lib/ui/widgets/patchesSelectorView/patch_item.dart
pubspec.yaml

chore: merge `dev` to `main`

---

lib/ui/views/installer/installer_viewmodel.dart

*sorry for spamming tiny PRs* 😅
resolves https://github.com/ReVanced/revanced-manager/issues/1396

refactor: fix patch log order to be consistent with settings order

---

app/schemas/app.revanced.manager.data.room.AppDatabase/1.json
app/src/main/java/app/revanced/manager/data/room/AppDatabase.kt
app/src/main/java/app/revanced/manager/data/room/options/Option.kt
app/src/main/java/app/revanced/manager/data/room/options/OptionDao.kt
app/src/main/java/app/revanced/manager/data/room/options/OptionGroup.kt
app/src/main/java/app/revanced/manager/data/room/selection/SelectionDao.kt
app/src/main/java/app/revanced/manager/di/RepositoryModule.kt
app/src/main/java/app/revanced/manager/domain/repository/PatchOptionsRepository.kt
app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt
app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/SelectedAppInfoScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/ImportExportSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/ImportExportViewModel.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/PatchesSelectorViewModel.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/SelectedAppInfoViewModel.kt
app/src/main/res/values/strings.xml

feat: remember patch options

---

app/src/main/java/app/revanced/manager/ui/component/CustomListItem.kt
app/src/main/java/app/revanced/manager/ui/component/GroupHeader.kt
app/src/main/java/app/revanced/manager/ui/component/SettingsListItem.kt
app/src/main/java/app/revanced/manager/ui/component/settings/BooleanItem.kt
app/src/main/java/app/revanced/manager/ui/screen/InstalledAppInfoScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/AboutSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/GeneralSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/ImportExportSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/update/UpdatesSettingsScreen.kt

feat(Settings): use SettingsListItem consistently and overall improvements

---

assets/i18n/en_US.json

When i open crowdin translation
It shows something like that:

Remove unnecessary punctuation

---

lib/services/manager_api.dart
lib/ui/views/installer/installer_view.dart
lib/ui/views/installer/installer_viewmodel.dart
lib/ui/views/navigation/navigation_view.dart

https://docs.flutter.dev/release/breaking-changes/android-predictive-back
> [!IMPORTANT]
> New release from flutter is required

feat: improve predictive back

---

lib/ui/views/installer/installer_viewmodel.dart

feat: updated logs

---

lib/services/patcher_api.dart
lib/ui/views/settings/settings_viewmodel.dart
pubspec.yaml

- fix: https://github.com/ReVanced/revanced-manager/issues/1527

fix: Incorrect duplicate filename handling when exporting files

---

lib/services/patcher_api.dart

feat: append patch version to the APK name while sharing/exporting

---

app/src/main/java/app/revanced/manager/util/PM.kt

|Before|After|
|-----|-----|
|![image](https://github.com/ReVanced/revanced-manager/assets/39409020/4e0deeba-76d4-4234-8078-00e70b93955b)|![image](https://github.com/ReVanced/revanced-manager/assets/39409020/98274270-1296-4445-aff4-aa394b6eeb5e)|

fix(app-selector): show patchable installed apps first

---

assets/i18n/en_US.json

feat: Simplify settings strings

---

lib/services/manager_api.dart
lib/ui/views/installer/installer_view.dart
lib/ui/views/navigation/navigation_view.dart

Replaces `WillPopScope` with `PopScope`

refactor: Replace deprecated `WillPopScope`

---

.github/workflows/release-build.yml

Only triggers the release workflow when certain files are changed.

ci: Specify paths in release workflow

---

lib/ui/views/installer/installer_view.dart

fix(PopScope): User able to exit patch screen when the installer is still running

---

app/src/main/java/app/revanced/manager/network/api/ReVancedAPI.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/MainViewModel.kt

Disables automatic updates in dev builds.

refactor: Disable update for dev build

---

android/app/build.gradle
android/build.gradle
android/settings.gradle
lib/ui/views/settings/settingsFragment/settings_update_language.dart
lib/ui/widgets/appSelectorView/not_installed_app_item.dart
lib/ui/widgets/patcherView/app_selector_card.dart
pubspec.lock
pubspec.yaml

- upgrades dependencies
- fixes depreciated build scripts
- fixed minor issues from dart analyzer

chore: upgrade dependencies

---

.github/workflows/release-build.yml

Build uploading is handled by semantic release.

ci: remove unnecessary upload

---

lib/ui/theme/dynamic_theme_builder.dart

fix: specify that dark theme is dark

---

lib/ui/views/settings/settingsFragment/settings_update_language.dart
pubspec.yaml

Improve language update settings

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

*sorry for the second, unnecessary PR*

docs: Fix issue template mistakes

---

lib/ui/theme/dynamic_theme_builder.dart

Added didChangeAppLifecycleState @ovverride for theme update for triggering theme-change.

fix: Follow system theme immediately

---

app/build.gradle.kts
app/src/main/res/resources.properties

https://developer.android.com/guide/topics/resources/app-languages @ https://canary.discord.com/channels/952946952348270622/1254172401910943774/1258412968077557873

feat: Automatic language detection

---

.github/workflows/pr-build.yml
.github/workflows/release-build.yml
.github/workflows/update-documentation.yml

This also enable caching for release build.
> [!WARNING]
> ⌛ Merging once build success without issues.

ci: Bump dependencies to latest

---

gradle.properties

Speed up build:tm:
Compilation Trials were done using Android Studio Koala Feature Drop | 2024.1.2 Canary 8
VM: JetBrains OpenJDK 64-Bit 17.0.11 amd64
Windows 11.0

build: Enable Gradle Configuration Cache

---

app/src/main/java/app/revanced/manager/domain/manager/PreferencesManager.kt
app/src/main/java/app/revanced/manager/ui/component/AvailableUpdateDialog.kt
app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/update/UpdatesSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/DashboardViewModel.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/UpdatesSettingsViewModel.kt
app/src/main/res/values/strings.xml

feat: Show manager update dialog

---

app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
app/src/main/java/app/revanced/manager/ui/viewmodel/PatchesSelectorViewModel.kt
app/src/main/res/values/strings.xml

feat: Improve unsupported patch warnings

---

lib/ui/views/app_selector/app_selector_viewmodel.dart

Have I test this? Nope.
What's my priority? Right, it's introduce feature instead of fixing bug :trollface: 
partially closes #2042 (flutter)

feat: Include primary architecture in external search

---

app/src/main/java/app/revanced/manager/util/RequestManageStorageContract.kt

Open the app-specific Manage all files permission dialog directly instead of apps list
Before PR:
After PR:

feat: Open the app-specific Manage all files permission dialog

---

assets/i18n/strings.i18n.json

Fixes https://github.com/ReVanced/revanced-manager/issues/2140

feat: Improve "Installation incompatible" dialog message

---

lib/ui/views/home/home_viewmodel.dart

https://github.com/ReVanced/revanced-manager/commit/81f05e1b190274d97427bd6b196cdc6d0a66757c#commitcomment-146549727
I checked this really fixes the issue

fix: Fix the connectivity check toast again

---

.github/workflows/sync_crowdin.yml

Red zone, decoration, description will be provided once I figured out how to use the CI
*maybe*

ci: Use the correct expression to grab translation files

---

app/src/main/java/app/revanced/manager/ui/screen/settings/ImportExportSettingsScreen.kt
app/src/main/res/values/strings.xml

feat: Reorder Import & Export settings

---

app/src/main/java/app/revanced/manager/ui/viewmodel/GeneralSettingsViewModel.kt
app/src/main/java/app/revanced/manager/util/Util.kt

Fix of https://github.com/ReVanced/revanced-manager/issues/2526
Most probably not done in the best way, sorry :)

fix(Compose): Reset cached theme on theme change

---

app/src/main/java/app/revanced/manager/patcher/runtime/ProcessRuntime.kt
app/src/main/java/app/revanced/manager/patcher/runtime/process/PatcherProcess.kt
app/src/main/java/app/revanced/manager/util/PM.kt

fix: patch count remaining at zero when using process runtime

---

app/src/main/java/app/revanced/manager/ui/model/BundleInfo.kt
app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt

Closes https://github.com/ReVanced/revanced-manager/issues/2538

feat(Compose): Improve patches selector tab by adding the bundle version

---

app/src/main/java/app/revanced/manager/MainActivity.kt
app/src/main/java/app/revanced/manager/ui/model/navigation/Nav.kt
app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/DeveloperSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/LicensesSettingsScreen.kt
app/src/main/java/app/revanced/manager/ui/screen/settings/update/ChangelogsSettingsScreen.kt

refactor: Rename settings screens for consistency

---

app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt

Already approved [here](https://github.com/ReVanced/revanced-manager/pull/2563) but I messed up with git branches.

fix: Correctly display universal patches warning

---

app/src/main/java/app/revanced/manager/data/room/bundles/PatchBundleDao.kt
app/src/main/java/app/revanced/manager/data/room/bundles/PatchBundleEntity.kt
app/src/main/java/app/revanced/manager/domain/bundles/LocalPatchBundle.kt
app/src/main/java/app/revanced/manager/domain/bundles/PatchBundleSource.kt
app/src/main/java/app/revanced/manager/domain/bundles/RemotePatchBundle.kt
app/src/main/java/app/revanced/manager/domain/repository/PatchBundlePersistenceRepository.kt
app/src/main/java/app/revanced/manager/ui/component/bundle/BundleInformationDialog.kt
app/src/main/java/app/revanced/manager/ui/component/bundle/BundleItem.kt
app/src/main/java/app/revanced/manager/ui/component/bundle/BundleSelector.kt
app/src/main/java/app/revanced/manager/ui/model/BundleInfo.kt

fix: display version from manifest
