ReVanced/revanced-manager

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
Fixes printing the stack trace of a failing patch instead of serializing an exception to a string.
=> fix: print stack trace of patch exceptions

lib/services/patcher_api.dart
Keystore files are currently located in cache, which gets deleted often.
This PR solves it by saving keystores in `externalStorageDirectory` (`Android/data/app.revanced.manager.flutter/files`), also gives users ability to backup keystore files.
=> fix: use permanent keystore path if available

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt, assets/i18n/en_US.json, lib/services/patcher_api.dart, lib/ui/views/installer/installer_view.dart, lib/ui/views/installer/installer_viewmodel.dart, pubspec.yaml
Allows users to export APK once it's patched. 
I'm using [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT) intent for export. This has it's benefits.
* We get to populate initial name for exported file, but user can edit before exporting
* We don't need to care about permissions and folder locations. We get a ContentUri and we just have to write apk there.
* Export is not limited to local filesystem. APK can be exported to other implementations like Google Drive out of the box.
Fixes: #140
=> feat: Adding support for Exporting APK

lib/ui/views/patches_selector/patches_selector_view.dart, lib/ui/widgets/patcherView/patch_selector_card.dart
This is nice to have when updating youtube revanced and you know how many patches you currently have applied.
It's easy to see if you forgot one or not instead of manually counting.
Feedback on how to make the code better very much appreciated.
=> feat: show selected patches count in patches selector view & patch selector card

lib/ui/views/app_selector/app_selector_viewmodel.dart
When picking an apk file with FilePicker from storage, the file gets cached. This is fine, but when you select a newer version of that file (because the patches now support a newer version of eg. youtube), the old apk file does not get removed from cache. I accumulated several youtube apks in my cache taking up a considerable amount of storage.
This PR simply deletes all other apks in the cache when selecting a new one.
=> fix: delete cached apk files when picking new one

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
This PR fix a issue that manager possibly apply wrong patch when there are 2 or more patch intended for different package name but have same patch name.
Issue: https://github.com/revanced/revanced-patches/pull/1082
If this issue was fixed then this https://github.com/revanced/revanced-patches/pull/1085 can be merged.
=> fix: the issue that makes `manager` apply the wrong patch when there are duplicate patch names.

.github/workflows/crowdin.yml, .github/workflows/debug-build.yml, .github/workflows/release-build.yml
This PR updates nearly all workflow actions (except for one which is abandoned, namely `marvinpinto/action-automatic-releases`).
Why is this needed?
Node.js 12 actions are deprecated and support for them could be removed at any point, see warnings like in [this](https://github.com/revanced/revanced-manager/actions/runs/3397952348) workflow.
I will also create PRs like this one in the other repos using outdated actions.
=> fix: update workflow actions

assets/i18n/en_US.json, lib/main.dart, lib/services/github_api.dart, lib/services/manager_api.dart, lib/ui/views/settings/settingsFragement/settings_manage_sources.dart
Adds the ability to pull patches & integrations from any Gitea repository.
This should help to reduce ReVanced's reliance on GitHub for supplying patches, at least until a more detailed/permanent solution is ready.
=> Support Gitea repositories for patches

android/app/build.gradle
This PR bumps the patcher version to be compatible with the latest patches which require the patcher `v6.3.2`.
=> build: bump patcher version

.github/ISSUE_TEMPLATE/bug-issue.yml
This PR fixes the issue on this repository of users opening issues unrelated to the ReVanced Manager by improving the label for the acknowledgement.
=> feat: clarify acknowledgement label

README.md
Just a minor fix that fixed this,
Invalid: https://github.com/revanced/revanced-documentation/blob/main/docs/revanced-development/2_building_from_source.md
Valid: https://github.com/revanced/revanced-manager/blob/docs/docs/5_building-from-source.md
=> chore: Update broken documentation link

lib/services/manager_api.dart, lib/ui/views/app_selector/app_selector_viewmodel.dart, lib/ui/views/patcher/patcher_viewmodel.dart, lib/ui/views/settings/settings_viewmodel.dart
=> refactor: cleanup remember patches feature

lib/services/patcher_api.dart, lib/ui/views/settings/settings_viewmodel.dart, pubspec.yaml
cr_file_saver had a bug that revanced manager had workarounds for in 2 places.
Updating the plugin, we can get rid of these workarounds.
1 of the workarounds is currently broken so this fixes that as well.
=> fix: update cr_file_saver

lib/ui/views/patches_selector/patches_selector_view.dart
In the patches selector screen, there are 3 buttons below the searchbar, 1 of which is a "select all" button.
The button in the searchbar is confusing and redundant.
=> refactor: remove select all icon from searchbar

lib/ui/theme/dynamic_theme_builder.dart, lib/ui/widgets/settingsView/custom_switch.dart
> **Note**: This PR only documented style(navbar, switch).
Follow the Material 3 specification for the navigation bar: https://m3.material.io/components/navigation-bar/specs#072e0aaf-cb7e-4ac1-9bec-356f40cce58f
Old
New
Improve accessibility when the toggle is in `dark mode` && `off state`, this does not follow the Material 3 specification due to a problem with accessibility. (insufficient contrast)
Old
New
=> style: use the correct m3 theming (partially)

lib/ui/views/patches_selector/patches_selector_view.dart
Add a fixed height of 500px to the textbox (apparently that works?)
> **A) Merging this PR fix #670**
> B) !! This problem doesn't exist in an older version of Flutter !! (Tested on Flutter 3.3.10)
=> feat: fix patch bundle version no longer displayed, closes #670

lib/ui/views/patches_selector/patches_selector_viewmodel.dart
With this PR on first load of the patches selector screen:
Without:
=> fix: display patches version on first load

.github/workflows/crowdin.yml
Ignore syncing translation to crowdin if the repository's owner is not "revanced".
> **Note**: Ignore crowdin translation sync if the repository's owner is not `revanced`, or else the workflow would fail immediately because of unspecified or invalid environment settings, and besides that, contributors don't need to do a translation sync as that'll be done by the upstream.
=> ci(crowdin): ignore translation sync if the repository's owner is not "revanced"

lib/theme.dart, lib/ui/theme/dynamic_theme_builder.dart, lib/ui/views/app_selector/app_selector_view.dart, lib/ui/views/contributors/contributors_view.dart, lib/ui/views/home/home_view.dart, lib/ui/views/installer/installer_view.dart, lib/ui/views/patcher/patcher_view.dart, lib/ui/views/patcher/patcher_viewmodel.dart, lib/ui/views/patches_selector/patches_selector_view.dart, lib/ui/views/settings/settings_view.dart, lib/ui/widgets/appInfoView/app_info_view.dart, lib/ui/widgets/homeView/available_updates_card.dart, lib/ui/widgets/homeView/installed_apps_card.dart, lib/ui/widgets/patchesSelectorView/patch_options_fields.dart, lib/ui/widgets/shared/custom_chip.dart, lib/ui/widgets/shared/custom_sliver_app_bar.dart
Improve the readability of the code.
> Migrate deprecated text style
> Migrate `toggleableActiveColor` to individual theme
> Don't use 'BuildContext's across async gaps
These changes were applied as suggested by the Flutter migration guide
=> chore: migrate deprecation code && code cleanup

.github/workflows/pull-request-build.yml, .github/workflows/release.yml
Enable GitHub cache to speed up workflows 
> Before caching: Actions usually take around 10\~ish minutes to complete
> With caching (first-run): Actions usually take around 15\~ish minutes to complete
> With caching (cached): Actions usually take around 6-8~ish minutes to complete
resolve: #611
<details>
<summary>Please don't look at the past Please don't look at the past Please don't look at the past Please don't look at the past Please don't look at the past</summary>
https://user-images.githubusercontent.com/93124920/227767135-bc7909db-6b63-4541-860d-fec490925b0f.png
</details>
=> ci: use caching to speed up workflows

.github/workflows/analyze.yml
Prevent unnecessary runs
The workflow will run on changes to lib/`.dart` and changes to the analyser itself.
resolve: #765
=> ci(analyze): only run when necessary

assets/i18n/en_US.json, lib/ui/widgets/settingsView/settings_advanced_section.dart
What a coincidence, this PR have almost the exact same wording as the issue that I was resolving.
Resolve: #566
<details>
> **Note**
> After the screenshot was taken, the `ok` button has been replaced with `yes` button.
</details>
=> feat: confirmation dialog for deleting keystore

lib/ui/views/settings/settingsFragment/settings_manage_sources.dart
Remove that extra space when trying to set custom source >:(
You can never set `"revanced      "` or `"  revanced   "` again :)
<details>
<summary>Preview</summary>
https://user-images.githubusercontent.com/93124920/230294728-4f75a702-cb23-497d-b74c-163a188dbad6.mp4
*pain*
</details>
=> feat: trim extra space when setting custom source

android/app/build.gradle, android/build.gradle, lib/services/github_api.dart, lib/services/manager_api.dart, lib/services/patcher_api.dart, lib/services/revanced_api.dart, lib/ui/views/home/home_viewmodel.dart, lib/ui/views/navigation/navigation_viewmodel.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/homeView/update_confirmation_dialog.dart, pubspec.yaml
Updated dependencies to latest version
- re-implemented cache interceptor using [dio_cache_interceptor](https://pub.dev/packages/dio_cache_interceptor) because [dio_cache_manager_lts](https://pub.dev/packages/dio_http_cache_lts) has not got any update for a while and is incompatible with latest [dio](https://pub.dev/packages/dio)
- migrated to latest [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) that include some breaking changes
- replaced native_dio_client with [native_dio_adapter](https://pub.dev/packages/native_dio_adapter)
- removed unused dependencies from pubspec.yaml
- minor code refactor
Everything is tested and working as per expectations
=> chore: update dependencies

lib/ui/widgets/contributorsView/contributors_card.dart
Opening links externally allows them to open in GitHub app if the user has it installed, if not, it opens in the browser.
=> fix: open contributor links externally

assets/i18n/en_US.json
Addressing issue raised by @Ushie in #818, clarify that things might (and likely will) not work as intended if you don't use the version stated.
Maybe using the phrase `Latest supported` would be better, but I don't want to give any possible illusion of "huh, it might still work, maybe its just not the latest" then at best wasting their own time, at worst wasting everyone else time to do tech support for him/her.
=> feat: improve suggested app version text

assets/i18n/en_US.json
This change provide suggestions on what to do in case of the very high chance of the patching process failing/aborting.
As shown in https://github.com/revanced/revanced-manager/issues/458#issuecomment-1529023135, people still don't know what to do when they see the warning. This PR aims to guide users on possible solutions to this problem.
The advice was adapted from the revanved bot in discord: 
> It seems like your Manager is aborting. If you see the text "exit code = 135" or "exit code = 139", then your devices architecture is not supported. Please patch on an another device or on your PC.
=> feat: clarify warning and consequences for ARMv7 users

pubspec.yaml
- Incorrect file name while exporting patched file if a file with the same name exists in the selected location.
- A change in the plugin is required that's implemented and update the corresponding dependencies
- closes: https://github.com/revanced/revanced-manager/issues/559
https://user-images.githubusercontent.com/53393418/235360013-c65598ed-fcc0-470b-b0ec-7ddb516981b8.mp4
=> fix: broken filename when saving files with the same name

android/gradle/wrapper/gradle-wrapper.properties
_Allows for verification for the downloaded binary using SHA-256 hash comparison. This increases security against targeted attacks by preventing a man-in-the-middle attacker from tampering with the downloaded Gradle and in rare case, attacker gets access to the Gradle servers._
- add `distributionSha256Sum` to Gradle properties
> * The checksum is provided here - https://gradle.org/release-checksums/
-----------------
- [Gradle documentation - **Configuring SHA-256 checksum verification**](https://docs.gradle.org/current/userguide/gradle_wrapper.html#downloading_the_sha_256_file)
=> feat: add checksums verification to Gradle

lib/ui/views/app_selector/app_selector_view.dart, lib/ui/views/contributors/contributors_view.dart, lib/ui/views/installer/installer_view.dart, lib/ui/views/patches_selector/patches_selector_view.dart
- Added spacing at the end to avoid view cutout when the system has 3 button navigation bar
Before            |  After
:-------------------------:|:-------------------------:
=> fix: system navigation overlapping UI at bottom

android/app/build.gradle
coreLibraryDesugaring is enabled, but it is actually not used because this app is minSdkVersion 26+.
Also remove WindowManager library which was added in the same commit (https://github.com/revanced/revanced-manager/commit/197770b68b0a2f93f91be746f1117699d47c01d6).
(He probably read [this page](https://pub.dev/packages/flutter_local_notifications#gradle-setup) and added it to avoid crashing.)
=> chore: remove coreLibraryDesugaring

lib/ui/views/home/home_viewmodel.dart
Fix: #894
There is already a "v" before the version number thanks to the workflow. So now it's useless to write it in the string.
=> fix: remove redundant "v" in the downloader screen

.github/workflows/analyze.yml
This change just remove the trigger for push to the repository. 
See description for 5cf441623a32c16d99b21b86fe47d0cc455fd7fb
<br>
> * Changelog came from commit description
<br>
`ci`: 5cf441623a32c16d99b21b86fe47d0cc455fd7fb - Not needed since we can't see the result in commit or just going to be hardly see by anyone. (note: I don't think that the `dart-analyze` tool can comment)
=> ci(analyze): don't run when pushed to repository

lib/ui/views/home/home_viewmodel.dart
The _latestManagerVersion returns empty string when comparing with the currentVersion. So, calling the _managerAPI.getLatestManagerVersion() before comparing fixes the logic and boolean is returned accordingly
Closes #890
=> fix: update button being shown as clickable on launch

lib/ui/widgets/patchesSelectorView/patch_item.dart
This includes hiding the "Warning" label on the disabled card as interacting with it only makes sense on an enabled card.
Before vs After:
=> feat(patches-selector): Improve disabled card UI

lib/services/revanced_api.dart
When a user clicks on cancel or outside the dialog box while downloading the update, managerUpdateProgress is closed. This results in completely canceling the Stream and that's why the user cannot download the update without re-launching the app.
Closes #936
=> fix(updater): ability to start again after cancelling

lib/ui/widgets/appSelectorView/installed_app_item.dart
=> feat(app-selector): Improve app item UI to avoid overflow issues

docs/2_1_patching.md
merging footnote 1 and 4; some more clarity for step 6
=> docs: small changes

assets/i18n/en_US.json, lib/services/revanced_api.dart, lib/ui/views/home/home_viewmodel.dart
When a user knowingly or unknowingly cancels or closes the installer window, there must be a dialog box which allows the user to launch the installer window again.
=> feat(updater): download successful dialog

lib/ui/widgets/patchesSelectorView/patch_item.dart, lib/ui/widgets/settingsView/settings_experimental_patches.dart
This PR fixes the issue with unsupported patches not being unselected even after the Experimental patches support is turned off.
Reproduce the issue by turning on Experimental patches support first, then select any unsupported patches and click done. Now, turn off the experimental patches support. Check the selected patches list and length is the same.
=> fix: experimental patches stay selected when toggled off

lib/services/github_api.dart
We have already been through the times when we push an update with lots of new features and fixes but due to some bugs, we immediately push a hotfix to resolve the issue. However, because of that hotfix, the changelog gets updated which just mentions about the hotfix and the users who didn't update the app before the hotfix won't be able to see all the new changes within the app while updating.
This PR fixes that problem by merging the changelogs.
For example: If I am on `v1.3.0`, then, I will be able to see the changelogs from `v1.3.1` upto the latest version.
=> feat: show all the unseen changelogs on changelog section

lib/ui/views/home/home_viewmodel.dart
When a user is offline, the call for the latest version is returned empty which results in the `if` logic returning true.
This PR fixes the issue by assigning the current version to the latest version if the latest version comes null.
Closes #986
=> fix: update button being clickable when offline

lib/services/github_api.dart, lib/ui/views/home/home_viewmodel.dart
This PR fixes #982 by using separate function to check for manager update so that the custom source don't use the same function because the custom source may not support the same logic as the default one.
=> fix: app crash after custom source

.github/ISSUE_TEMPLATE/bug-issue.yml
Clarified acknowledgements in bug issue form
Prompted by [this discussion](https://github.com/revanced/revanced-patcher/issues/205#issuecomment-1627727173)
=> refactor: Acknowledgements in bug issue form

.github/ISSUE_TEMPLATE/bug-issue.yml, android/app/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, assets/i18n/en_US.json, docs/1_installation.md, lib/services/github_api.dart, lib/services/revanced_api.dart, lib/ui/views/app_selector/app_selector_view.dart, lib/ui/views/home/home_viewmodel.dart, lib/ui/views/navigation/navigation_view.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/appSelectorView/app_skeleton_loader.dart, lib/ui/widgets/appSelectorView/installed_app_item.dart, lib/ui/widgets/appSelectorView/not_installed_app_item.dart, lib/ui/widgets/homeView/update_confirmation_dialog.dart, lib/ui/widgets/patchesSelectorView/patch_item.dart, lib/ui/widgets/settingsView/settings_experimental_patches.dart, lib/ui/widgets/settingsView/settings_export_section.dart, pubspec.yaml
Prerequisite before merge
--------------------
16 Commits (1+4+3+5+2+1)
* ✨ 1 Feature
* 🐛 4 Bug Fixes
* ⚙️ 3 Build Changes
* ♻️ 5 Code Refactoring
* 📝 2 Documentation Improvements
* 🧹 1 Miscellaneous Change
--------------------
ReVanced Manager v1.3.9 (Next)
Experienced in Kotlin? Consider checking out [ReVanced Manager Compose](https://github.com/revanced/revanced-manager-compose)!
=> chore: merge `dev` branch to `main` branch

lib/services/root_api.dart
This should fix:
```
Unhandled Exception:
Unsupported operation: Cannot add to a fixed-length list
```
=> fix: Prevent `Unsupported operation` exception

lib/services/patcher_api.dart, lib/ui/views/home/home_viewmodel.dart, pubspec.yaml
=> fix: showing `Installed` when it's actually not

lib/ui/views/settings/settingsFragment/settings_manage_api_url.dart
- Close previous dialog when the user reset the API URL
Before            |  After
:-------------------------:|:-------------------------:
=> fix: close previous dialog when user reset the API URL

lib/services/patcher_api.dart, lib/services/root_api.dart
The manager has no permissions to access the contents of `/data/adb` folder. So, it is not detecting the `revanced` folder and its contents. When the `original.apk` file actually exists when checked on the Flutter side, the path is invoked to the Android side which is not accessible. To solve the issue, we can directly use the `apkFilePath` as the `originalFilePath` without using the root method.
=> fix: `original.apk` not found despite existing

assets/i18n/en_US.json, lib/main.dart, lib/services/github_api.dart, lib/services/manager_api.dart, lib/services/revanced_api.dart, lib/ui/views/app_selector/app_selector_viewmodel.dart, lib/ui/views/home/home_view.dart, lib/ui/views/home/home_viewmodel.dart, lib/ui/views/patches_selector/patches_selector_viewmodel.dart, lib/ui/views/settings/settingsFragment/settings_manage_sources.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/homeView/latest_commit_card.dart, lib/ui/widgets/homeView/update_confirmation_dialog.dart, lib/ui/widgets/settingsView/settings_advanced_section.dart, lib/ui/widgets/settingsView/settings_auto_update_patches.dart
This PR aims to allow users to choose whether the ReVanced Patches are updated to the latest one automatically or manually at anytime they want. Right now, users are automatically served with latest patches. This results in users not noticing a new patch or new patchable app easily. When this PR gets merged, they will be able to read the changelogs when updating manually and make the decision to update accordingly.
=> feat: allow control over patches update

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt, assets/i18n/en_US.json, lib/services/patcher_api.dart, lib/ui/views/installer/installer_viewmodel.dart
This PR aims to allow users to abort the patching process whenever they want so that they can include/exclude patches or change the app without having to restart the manager.
Make sure the following tasks are completed. Without this, the patching process can be aborted but cannot be started again without restarting the manager.
=> feat: abort patching process at any time

lib/services/patcher_api.dart, lib/ui/views/patches_selector/patches_selector_viewmodel.dart
=> fix(patch-item): hide universal patches if not enabled

lib/ui/views/patcher/patcher_viewmodel.dart, lib/ui/widgets/patchesSelectorView/patch_item.dart, lib/ui/widgets/settingsView/settings_experimental_patches.dart, lib/ui/widgets/settingsView/settings_experimental_universal_patches.dart
This PR aims to fix issues regarding the experimental and universal patches being used in the patching process even when the `Experimental patches support` and `Experimental universal patches support` are turned off. Here's a before-and-after of experimental patches because I created this PR for that. Now, I changed it to both.
|Before|After|
|------|----|
|<video src="https://github.com/ReVanced/revanced-manager/assets/39409020/d007737f-6c3f-4d55-810f-8101c23bc1e8">|<video src="https://github.com/ReVanced/revanced-manager/assets/39409020/65b719f5-befa-42ab-8886-b1b457c44e57">|
=> fix: experimental/universal patches being used even when turned off

lib/services/manager_api.dart, lib/ui/views/home/home_viewmodel.dart
This PR fixes the issue related to the integrations file being updated to the latest version automatically, causing issues in the patching process when the ReVanced Patches being used are not the latest.
=> fix: pair integrations and patches updates

lib/services/github_api.dart, lib/services/manager_api.dart, lib/services/patcher_api.dart, lib/ui/views/home/home_viewmodel.dart, lib/ui/views/settings/settingsFragment/settings_manage_sources.dart
This PR allows the manager to make use of the cache files (patches and integrations) while offline
When the files are not there and also no internet, then the users just see, "no applications" text in the app selector page like they used to 
https://github.com/ReVanced/revanced-manager/assets/39409020/1aa7dcd4-d4e6-41d9-9051-8389a95123b1
=> feat: patch apps without internet

android/app/build.gradle
Add abiFilters to exclude x86 native libraries for release builds.
Because the x86 aapt2 binary causes crash on x86 devices.
Flutter doesn't support x86 for release build.
So, when running Flutter apps on x86 devices, usually armv7 `libflutter.so` and `libapp.so` are loaded through ARM emulation.
https://github.com/flutter/flutter/issues/9253#issuecomment-665736044
However, If the app contains one or more x86 libs, Android OS only loads native libraries in libs/x86/.
Then the app can't load `libflutter.so` and crashes with `UnsatisfiedLinkError`.
Therefore, the x86 aapt2 binary has no reason to exist in release builds.
Also, this reduces APK size by 3MB.
<details>
Unfortunately, I don't have any actual x86 devices, so I tested on an Android Emulator which supports ARM emulation.
```
08-09 …
```
=> fix: exclude x86 aapt2 binary from release builds

assets/i18n/en_US.json, lib/services/manager_api.dart, lib/ui/views/patcher/patcher_viewmodel.dart, lib/ui/views/patches_selector/patches_selector_view.dart, lib/ui/views/patches_selector/patches_selector_viewmodel.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/patchesSelectorView/patch_item.dart, lib/ui/widgets/settingsView/settings_advanced_section.dart, lib/ui/widgets/settingsView/settings_allow_patches_selection.dart, lib/ui/widgets/settingsView/settings_enable_patches_selection.dart, lib/ui/widgets/settingsView/settings_export_section.dart
This PR aims to disable changing the default patches selections until the users enable it in the settings.
=> feat: disable changing patches selection by default

.gitignore
Ignore the root .gradle folder that is created in [step 4 of building](https://github.com/ReVanced/revanced-manager/blob/main/docs/4_building.md)
=> chore: ignore the root .gradle folder

lib/ui/views/installer/installer_view.dart
Fix: #1170 (bug: No way to open the patched app right after installation)
=> fix(installer): open the patched app after install

settings.gradle.kts
Because of gradle/gradle#23572, `providers.gradleProperty` can not see other `gradle.properties` files. This should temporarily fix that until the Gradle issue is resolved.
This now allows the use of `~/.gradle/gradle.properties` to store GitHub tokens instead of `~/gradle.properties`.
=> fix: providers.gradleProperty

app/proguard-rules.pro
fixes: #1240 
Minify was previously warning about `com.google.j2objc.annotations.*`, causing it to crash. So a `-dontwarn` argument was added to the proguard rules.
=> fix: minify crash on building release

lib/services/patcher_api.dart
An attempt to improve the app page loading speed when universal patches have been enabled.
I suspect that the `DeviceApps.getInstalledApplications` and `DeviceApps.getApp` functions are slowing it down, though I have applied some other optimizations to improve the speed slightly.
=> fix: Improve app list loading speed

app/src/main/java/app/revanced/manager/network/dto/ReVancedContributors.kt
Due to the ReVanced API calling contributor usernames `login` and not `username`, the contributors screen broke.
=> fix: contributors screen fix

app/src/main/java/app/revanced/manager/ui/screen/settings/ImportExportSettingsScreen.kt, app/src/main/res/values/strings.xml
Updated the string name from `import_keystore_descripion` to `import_keystore_description`
=> fix: typo in string name `import_keystore_description`

lib/services/manager_api.dart
solve #1280
because casing doesn't matter here
rEVanCED/ReVANCED-pATChEs is the same as revanced/revanced-patches
ex :
try https://github.com/rEVanCED/ReVANCED-pATChEs/releases/latest and https://github.com/revanced/revanced-patches/releases/latest
you can notice you end on exactly the same page
=> fix(custom-sources): ignore casing when checking if default repo is being used

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt, lib/services/github_api.dart, lib/services/manager_api.dart, lib/services/patcher_api.dart
=> fix: load patches via `PatchBundle`

app/build.gradle.kts
Appends `.debug` to the `applicationId` so that the debug version and release version of the manager can be installed at the same time.
=> feat: change appID and name of debug builds

assets/i18n/en_US.json, lib/services/manager_api.dart, lib/ui/theme/dynamic_theme_builder.dart, lib/ui/views/navigation/navigation_viewmodel.dart, lib/ui/views/settings/settingsFragment/settings_update_theme.dart
=> feat: follow the system theme

lib/ui/theme/dynamic_theme_builder.dart
I guess the brightness variable was not initialized in time, thus when starting it causes the it to use the light theme
=> fix: default theme not following system

app/src/main/java/app/revanced/manager/ui/component/bundle/BaseBundleDialog.kt
The button to view the available patches inside a bundle has been update to allow the entire row to be clickable similar to the rest of the interactable elements.
=> fix(ui): make entire patches view button selectable

app/src/main/java/app/revanced/manager/ui/component/Markdown.kt
When using the `WebView` element for rendering Markdown, it would remember history and take control over the back button. For example, within the changelog pressing the back button on the Android Nav Bar removes the Markdown text or reverts the text to `Loading Changelog...` instead of going back to the previous screen.
=> fix: disable `WebView` history

app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt
The `onBackClick` argument was not specified for `UpdateProgressScreen`.
=> refactor: update progress onBackClick function

lib/ui/views/navigation/navigation_viewmodel.dart
=> fix: force disable material you on Android 11 and below

lib/ui/views/navigation/navigation_viewmodel.dart, pubspec.yaml
We removed the ability for the app to flashbang user when using light mode on Android 11 and under.
=> chore: merge `dev` to `main`

app/src/main/java/app/revanced/manager/ui/screen/settings/AboutSettingsScreen.kt, app/src/main/res/drawable/ic_logo_ring.xml
This allows the logo to stand out more on a dark background.
=> fix: use ReVanced ring logo in about section

lib/ui/views/patches_selector/patches_selector_viewmodel.dart
|Before|After|
|---|---|
|<img height="349" alt="image" src="https://github.com/ReVanced/revanced-manager/assets/39409020/18d20250-7d28-45a6-aca4-db7737c1c0b6">|<img width="349" alt="image2" src="https://github.com/ReVanced/revanced-manager/assets/39409020/e7929a1d-cf7f-4215-a725-ed9914170385">|
=> fix(patches-selector): ignore punctuation marks when searching for patch

lib/ui/widgets/patchesSelectorView/patch_options_fields.dart
This disables the ability to tap on the card because it leads to nothing, and possibly avoiding confusion among user in Discord...
=> refactor(Patch Options): disable card tap

assets/i18n/en_US.json, lib/ui/views/patch_options/patch_options_view.dart, lib/ui/views/patch_options/patch_options_viewmodel.dart
Improve accessibility, and avoid user from accidentally resetting their patch options
Changed from Secondary Container to Surface to provide slightly better hierarchy.
Ignore commit message, something messed up
Yes, my budget for writing PR has temporarily dropped :trollface:
=> refactor(Accessibility): improve patch options

lib/ui/views/installer/installer_viewmodel.dart
Adds patch options to error log.
Example:
```
~ Device Info
ReVanced Manager: 1.13.1
Build: debug
Model: SM-G973U1
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
~ Patch Info
App: com.google.android.youtube v18.38.44
Patches version: v2.194.0
Patches: Alternative thumbnails, Always autorepeat, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom player overlay opacity, Disable Shorts on startup, Disable auto captions, Disable fine scrubbing gesture, Disable player popup panels, Disable zoom haptics, Enable debugging, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, …
```
=> feat: show patch options in error log

lib/ui/views/installer/installer_viewmodel.dart
This add root status to the log.
* Samsung M23 5G (Android 13; One UI 5.1)
* #1405
=> feat: root status in export patch log

lib/ui/views/patches_selector/patches_selector_view.dart, lib/ui/views/patches_selector/patches_selector_viewmodel.dart
This PR fixes the issue where category labels were still visible even when the list was empty. It also addresses code duplicity and improves code efficiency.
=> fix: hide empty patches category labels

docs/4_building.md
the ~ symbol leads to the home directory, I changed it to . so  it can point to the current directory
=> docs: use correct directory path

app/src/main/java/app/revanced/manager/ui/viewmodel/SelectedAppInfoViewModel.kt
When loading an APK, manager crashes with `java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied`.
=> fix: option state crash

assets/i18n/en_US.json, lib/services/manager_api.dart, lib/ui/views/app_selector/app_selector_view.dart, lib/ui/views/app_selector/app_selector_viewmodel.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/settingsView/settings_advanced_section.dart, lib/ui/widgets/settingsView/settings_require_suggested_app_version.dart
<image height="640" width="572" src="https://github.com/ReVanced/revanced-manager/assets/39409020/e3cc52a4-5a4d-4775-be04-783570cfd106"/>
=> feat: Disable selection of unsuggested app version by default

.github/workflows/pr-build.yml, .github/workflows/release-build.yml
There isn't any major changes other than bump from Node 16 to Node 20
=> ci: use migrate setup-java to Node 20

lib/ui/views/installer/installer_viewmodel.dart
```
- Patch Info
App: com.google.android.bleep.bloop.gah v1.33.7 (Suggested: Any)
Patches version: v2.202.0
Patches added: Packground Blay, Banced MicroG support
```
Closes #1552 #1550
=> feat: output suggested version into patch log

docs/3_troubleshooting.md
Document advice that could help users troubleshoot issues like https://github.com/ReVanced/revanced-manager/issues/1493 and https://github.com/ReVanced/revanced-manager/issues/1511 and https://github.com/ReVanced/revanced-patches-template/issues/114 without needing to contact support.
=> docs: Improve troubleshooting solutions

lib/services/root_api.dart
`root_api.dart` was preventing manager from building, so now it should be fixed.
=> fix: Mount script causes build to fail

lib/services/manager_api.dart
Having `ReVanced` be capitalized causes issues when trying to get the contributors for each repo, as the api returns the repos in lowercase.
=> fix: use lowercase repo names

analysis_options.yaml, pubspec.yaml
Removes unused dependencies:
- `flex_color_scheme`
- `flutter_dotenv`
- `flutter_launcher_icons`
- `flutter_svg`
- `flutter_test`
- `get_it`
- `http`
- `pull_to_refresh`
(I also decided to sort the dependencies alphabetically)
=> chore: remove unused dependencies

assets/i18n/en_US.json, lib/ui/views/app_selector/app_selector_viewmodel.dart, lib/ui/views/installer/installer_viewmodel.dart, lib/ui/views/patcher/patcher_viewmodel.dart, lib/ui/widgets/appSelectorView/installed_app_item.dart, lib/ui/widgets/appSelectorView/not_installed_app_item.dart, lib/ui/widgets/patcherView/app_selector_card.dart
This PR improves the app selector app item UI by simplifying it:
Before | After 
-|-
- Improved the suggested version chip padding
- Show the suggested version chip only if it does not match the installed version and is not "any version" in the patcher screen
- Moved patch count and version next to app name
- Corrected sizes and paddings
- Simplify strings such as "Select application" -> "Select app"
- Make this look better:
- Correct sizing/padding:
=> feat: Improve app selector UI

.github/workflows/release-build.yml
The version code forgot to include the major version in the number, which is why the new dev release is on `1900001` instead of `101900001`.
=> fix: use correct version code & name

assets/i18n/en_US.json, lib/services/github_api.dart, lib/services/manager_api.dart, lib/services/revanced_api.dart, lib/ui/views/home/home_viewmodel.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/homeView/latest_commit_card.dart, lib/ui/widgets/homeView/update_confirmation_sheet.dart, lib/ui/widgets/settingsView/settings_advanced_section.dart, lib/ui/widgets/settingsView/settings_show_update_dialog.dart
This PR fixes #1637 and also blocks any API requests until the users agree to download ReVanced Patches.
Screenshots
<image height="640" width="572" src="https://github.com/ReVanced/revanced-manager/assets/39409020/a67e01ba-92db-4771-871f-af3777ca74b1" alt="update-dialog"/>
=> feat: Show a dialog when an update is available

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
fix #1253
Currently, even if an error occurred while signing apk, the patching process appears as if it is completed.
Therefore, the patched APK (`out.apk`) was not actually output, and the [Export APK] button causes a crash.
```
09-09 13:33:45.253 10011 10011 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AXYSFX/out.apk: open failed: ENOENT (No such file or directory)
```
This issue (#1253) is caused by the double nested `try` block.
Any exceptions that occur while signing apk will be ignored by the try block.
Only a stack trace is output to logcat, but user will have never seen it.
```
--------- beginning of main
09-09 13:33:41.059 10011 12502 W System.err: java.security.UnrecoverableKeyException: no match
09-09 13:33:41.059 …
```
=> fix: Stop patch when signing fails

.releaserc.js
Adds scope to the changelog, plus it now checks for other commit types like `chore` and `ci`.
=> ci: add scope to changelog

.github/dependabot.yml, .github/workflows/release-build.yml, .releaserc.js, package-lock.json, package.json
Allows ci to build on commits with types such as `refactor`.
Also, while making changes, I noticed there were 2 high level vulnerabilities in the npm packages. There seems to be no fix for them at the moment, but I also added Dependabot so that they can be fixed as soon as possible.
=> ci: Accept more commits + Dependabot

lib/ui/views/app_selector/app_selector_view.dart, lib/ui/views/app_selector/app_selector_viewmodel.dart
The `model.allApps` is a list of already filtererd applications that are not installed on device. It's needed to check both arrays if they are empty.
=> fix: App list is empty if all apps are installed

lib/ui/views/home/home_viewmodel.dart
This PR closes #1741.
The *Changelogs Modal Bottom Sheet*  overlaps with the *Notifications Bar* (system intrusion) because the Modal Sheet is not constrained by a safe area. 
- **Issue:** The `Safe Area` constraints are not correctly applied on the *Changelogs* `Modal Bottom Sheet`.
- **Context:** The changelogs showed with `showModalBottomSheet`, are called without the `useSafeArea` property, causing a visual overlap with the notifications bar, when the modal sheet occupies the whole screen.
- **Related Solutions:** No related solutions at first sight. Should be fixed by adding the missing [useSafeArea][usesafearea] parameter.
- **Impact:** By addressing this issue, the visual overlap will no longer occur, making an important improvement to all users readability, enhancing the overall …
=> fix: Ensure safe area usage in Changelogs Modal Bottom Sheet (1741)

android/app/build.gradle, android/settings.gradle
The kotlin-stdlib dependency was bumped to 1.9.22, but the kotlin version is not bamped and it's still 1.9.10.
Bump Kotlin Gradle plugin, too.
Kotlin is bumped to 1.9.23.
In addition, `kotlin-stdlib` declaration is no longer needed from Kotlin 1.4.0, so I removed it.
> *"You no longer need to declare a dependency on the stdlib library in any Kotlin Gradle project"*
> https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default
(In the latest new Flutter project template, it has already been removed.)
=> build: Bump dependencies

lib/ui/views/settings/settingsFragment/settings_manage_api_url.dart, lib/ui/views/settings/settingsFragment/settings_manage_keystore_password.dart, lib/ui/views/settings/settingsFragment/settings_manage_sources.dart
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/validcube/validcube/main/assets/ReVancedManager/dynamic-dark.webp">
</picture>
@MarcaDian created an issue with our source switcher regarding the [`[AlertDialog]`](https://api.flutter.dev/flutter/material/AlertDialog-class.html) [`[title]`](https://api.flutter.dev/flutter/material/AlertDialog/title.html) being too long and caused the [`[IconButton]`](https://api.flutter.dev/flutter/material/IconButton-class.html) to overflowed out of the view here:
* #1790 
The relevant code was line 30-40 in Settings Fragment - [Manage Sources](https://github.com/ReVanced/revanced-manager/blob/main/lib/ui/views/settings/settingsFragment/settings_manage_sources.dart#L30-L40) …
=> fix: Replace Spacer with Expanded to avoid overflow

lib/ui/views/installer/installer_view.dart, lib/ui/views/installer/installer_viewmodel.dart
This PR fixes #1736, reported by @KobeW50 
The installer logs' functionality has been enhanced by introducing a dynamic auto-scroll feature, **Allowing free scrolling when the user pans** the scroll. However, if the user **scrolls down to the bottom or hits the auto-scroll-button** it will **lock in-place** again  improving the user experience/curiosity during the installation processes. 
- **Issue:** The Installer Logs always scrolls down on any log update disturbing the user reading experience (being a sh* annoying imo xD).
- **Context:** The current functionality lacks dynamic autoscroll behavior, forcing a repaint, auto-scrolling to then afterwards (after 1 sec of the listeners notification - yup, a magic number).
- **Related Solutions:** Similar to Discord's autoscroll behavior, the …
=> fix(ui): Support free-scroll and auto-scroll for the installer logs (#1736)

lib/ui/views/app_selector/app_selector_viewmodel.dart
I couldn't reproduce the issue. However, from my research, I found that providing the `mimeTypesFilter` to the file picker solves the issue. This also allows us to remove the `fileExtensionsFilter`.
=> fix: Do not crash when selecting an APK from storage

lib/services/github_api.dart
https://github.com/ReVanced/revanced-manager/issues/1776#issuecomment-2115827977
Make github_api to use Lock (synchronized) like revanced_api
This reduces GitHub API rate limit exceedance.
=> fix: Cache external API calls 

lib/ui/views/settings/settingsFragment/settings_update_language.dart
=> fix: Follow language update immediately

lib/ui/views/settings/settingsFragment/settings_manage_sources.dart
This PR closes #1748
The `AlertDialog`'s scrolling behavior for `showSourcesDialog` was causing children to clip, affecting user experience and readability, especially on devices with small screens or large fonts.
- **Issue:** Children (form fields) were clipping within the `AlertDialog`.
- **Context:** The structure for managing scrolling behavior was not efficient, leading to readability issues.
- **Related Solutions:** No similar solution available.
- **Impact:** Enhances readability and usability on various devices, ensuring a smoother user experience. (For smaller devices & devices with large fonts).
This PR addresses the issue of children clipping within the `AlertDialog` by adjusting the structure to handle scrolling more efficiently. It removes unnecessary scroll components and …
=> fix: Adjust scroll from clipping children form fields in `AlertDialog` from `showSourcesDialog`

lib/ui/views/home/home_view.dart, lib/ui/views/home/home_viewmodel.dart
This change adjusts the edge offset for the RefreshIndicator in the home view dashboard UI with the CustomSliverAppBar maxExtent size, ensuring a better user experience by moving the RefreshIndicator under the SliverAppbar.
> ##### Fixes #1568
The HomeView / Dashboard `[CustomScrollView]` refresh functionality has been enhanced by matching the starting refresh position with the `[SliverAppBar]` height, and by reducing the displacement range to settle the refresh.
- **Issue:** The RefreshIndicator starts the animation on top of the `[SliverAppBar]`, disturbing the user experience (?).
- **Context:** The current functionality lacks an increased starting point (`[edgeOffset]`) or a better layout.
- **Related Solutions:** (None).
- **Impact:** Improves the user experience by making the …
=> fix: Increase dashboard RefreshIndicator edge offset

lib/ui/widgets/patchesSelectorView/patch_item.dart
When I tried selecting unsupported patches, wrong text is shown.
This is a forgotten migration from flutter_i18n.
I confirmed that there were no other missed migrations.
=> fix: unsupported patch toast says "patchItem.unsupportedPatchVersion"

assets/i18n/strings.i18n.json, lib/ui/views/home/home_viewmodel.dart
While I was translating the Manager in Crowdin, I found unused strings.
Removing unused strings helps translators.
=> refactor: Remove unused strings

android/app/build.gradle, lib/ui/widgets/patchesSelectorView/patch_options_fields.dart, pubspec.lock
A plugin says it requires NDK version `26.1.10909125`, so the NDK version has been changed from `flutter.ndkVersion` to `26.1.10909125`
=> chore: Remove NDK constraint

app/src/main/java/app/revanced/manager/patcher/aapt/Aapt.kt, app/src/main/res/values/strings.xml, docs/0_prerequisites.md
Binary taken from run https://github.com/ReVanced/aapt2/actions/runs/9977958347
=> fix: Support patching on ARMv7 by updating AAPT2 

app/src/main/java/app/revanced/manager/domain/manager/base/BasePreferencesManager.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt, app/src/main/res/values/strings.xml
=> feat: Add reset button to custom API

lib/ui/views/installer/installer_view.dart, lib/ui/views/navigation/navigation_viewmodel.dart
=> fix: Patching Screen draw-behind Navigation Bar

lib/ui/views/installer/installer_viewmodel.dart, lib/ui/widgets/settingsView/settings_last_patched_app.dart, pubspec.lock
=> fix: Don't crash installation when saving last APK is disabled

lib/app/app.dart, lib/ui/widgets/appInfoView/app_info_viewmodel.dart
The install button for the last patched APK broke when `installTypeDialog` [was moved](https://github.com/ReVanced/revanced-manager/commit/c7627ced8eee19cd44945ea4388b2ffe5e38b138) to `InstallerViewModel`.
This PR unbreaks that change.
=> fix: Don't crash when installing the last patched APK

lib/ui/widgets/settingsView/settings_last_patched_app.dart
The save last APK did not have haptics applied to it. Now it does.
=> fix: Add haptics to save last APK switch

app/src/main/java/app/revanced/manager/data/platform/Filesystem.kt, app/src/main/java/app/revanced/manager/patcher/Session.kt, app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt, app/src/main/java/app/revanced/manager/ui/viewmodel/AppSelectorViewModel.kt, app/src/main/java/app/revanced/manager/ui/viewmodel/PatcherViewModel.kt
fix for #2120
The "ephemeral" directory is moved from cacheDir to filesDir.
The input.apk (exists if selected from storage) is moved to the ephemeral directory.
I'm not sure if the changes in `Session.kt` are right.
This is intended to delete input.apk as soon as possible when it is no longer needed.
If the apk is a downloaded apk or selected from installed apps, nothing happens on that line.
=> fix: Move temporary files outside of the cache directory

app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/DeveloperOptionsScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/GeneralSettingsScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/ImportExportSettingsScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/LicensesScreen.kt, app/src/main/res/values/strings.xml
=> feat: Improve Settings order

lib/services/manager_api.dart, lib/ui/widgets/patchesSelectorView/patch_options_fields.dart, pubspec.yaml
closes https://github.com/ReVanced/revanced-manager/issues/1703
=> fix: Handle selecting files and folders for patch options correctly

android/app/src/main/res/raw/revanced_manager_keep.xml
Drawable resource "ic_notification" is removed by shrinkResources and patching notification icon turns black.
Fix this issue by adding keep.xml file.
https://developer.android.com/build/shrink-code#keep-resources
↓
```
E/flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_icon, The resource ic_notification could not be found. Please make sure it has been added as a drawable resource to your Android head project., null, null)
E/flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
E/flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter : <asynchronous suspension>
E/flutter : #2 …
```
=> fix: Fix missing notification icon when shrinking resouces

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt, lib/services/manager_api.dart
Every time Manager starts, an empty directory is created in `/data/data/app.revanced.manager.flutter/cache/cache/` .
Use a native [`getCodeCacheDir()`](https://developer.android.com/reference/android/content/Context#getCodeCacheDir()) for the optimizedDexDirectory.
This is a right place to use for optimizedDexDirectory.
=> fix: Empty “tmp-XXXXXX” directory keeps growing in cacheDir

android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt
Sometimes, when there is an attempt to patch an App, that APK is only marked as `r-x` and not `rwx`.  
This can cause the patch to fail, as it cannot read the file after copying it to `patcher/tmp-.../in.apk` 
This PR Fixes that issue (as far as i can tell; tested with brand new install of revanced manager, with and without patch. To Verify)
=> fix: Resolve EACCESS error in special cases

app/src/main/res/values/strings.xml
#2140 has been solved on both Flutter and Compose, but Flutter Manager has a better message that was reviewed by oSumAtrIX. (#2164)
I think it is better to reflect it to Compose Manager also.
=> fix: Match "Installation incompatible" dialog message with Flutter Manager

assets/i18n/strings.i18n.json, lib/ui/views/patcher/patcher_viewmodel.dart
|Before|After|
|---|---|
|![before](https://github.com/user-attachments/assets/3c19f2fc-7d23-4f35-adb8-9435a97d78e2)|![after](https://github.com/user-attachments/assets/7e48db3e-0dba-4a6c-bf96-60bda07da771)|
=> feat: Also show new patches in the removed patches dialog

lib/services/github_api.dart, lib/services/manager_api.dart, lib/ui/views/home/home_viewmodel.dart, lib/ui/views/installer/installer_viewmodel.dart, lib/ui/views/settings/settingsFragment/settings_manage_sources.dart, lib/ui/views/settings/settings_viewmodel.dart, lib/ui/widgets/homeView/update_confirmation_sheet.dart
This PR aims to add the following features:
* Show changelogs from the latest to the last used patches version or up to 10 changelogs, whichever comes first.
* Save which patches version was used from which source and apply the correct last used version when the user reverts to the source.
=> feat: Show changelogs from the latest to the last used patches version

app/src/main/java/app/revanced/manager/ui/screen/BundleListScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
Column list of patch bundles is now scrollable by this changes.
=> feat: Make patch bundles list scrollable

lib/services/patcher_api.dart, lib/ui/views/installer/installer_viewmodel.dart
Instead of deleting the cached APK from the file picker **before** patching, the manager will now only delete it **after** patching.
=> fix: Delete cached APK after patching

app/src/main/java/app/revanced/manager/ui/component/CheckedFilterChip.kt, app/src/main/java/app/revanced/manager/ui/component/SearchBar.kt, app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt, app/src/main/java/app/revanced/manager/ui/viewmodel/PatchesSelectorViewModel.kt, app/src/main/res/values/strings.xml
This redesigns the patcher screen to reduce clutter. The search bar is now expandable, the patch count is displayed in a bottom bar and the reset button floats neatly above the save button. I added a clear button to the search bar to clear the queries. The filter chips now have a checkmark when selected and the filters have been reworded.
| Before | After |
|--------|-------|
|![image](https://github.com/user-attachments/assets/6694ca74-6c90-47c9-92b8-187ca2389d7b)|![image](https://github.com/user-attachments/assets/2c944272-77cd-45b0-bbc3-d765514284e7)|
New patcher screen in action:
[Screen_recording_20250109_003652.webm](https://github.com/user-attachments/assets/ffbef204-2118-486a-a162-ff7c37c31b77)
=> feat: Redesign the patches screen

.github/workflows/release-build.yml
Support GitHub Attestation for attesting the binary, matched SLSA requirements *level 2* which provides secure provenance for verification of authenticity of thg APK before installing onto devices.
=> ci: Generate release artifact provenance (Compose)

app/src/main/java/app/revanced/manager/ui/model/BundleInfo.kt, app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt, app/src/main/java/app/revanced/manager/ui/viewmodel/PatchesSelectorViewModel.kt, app/src/main/java/app/revanced/manager/ui/viewmodel/SelectedAppInfoViewModel.kt, app/src/main/res/values/strings.xml
=> fix: Use `compatible` rather than `support` when referring to patch compatibility

lib/ui/widgets/patchesSelectorView/patch_options_fields.dart
=> fix: Crash using when Integer type in Patch Options

android/app/proguard-rules.pro
This is ProGuard Shenanigans that I don't understand.
=> fix: Unable to Share Logs due to CCE in FileProvider

lib/utils/check_for_supported_patch.dart
Correct it to Kotlin type, and also
Print unsupported required patch option type in the future for Debug user for easier identifying which is troublesome
=> fix: Correct supported required patch option types 

app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt, app/src/main/java/app/revanced/manager/ui/viewmodel/DashboardViewModel.kt
An update for cf3866f892da8ca246d49f250e78139ccb3d87a1
Polling is not necessary by using StartActivityForResult
=> fix: Do not poll battery optimization status

lib/services/manager_api.dart
- Fixes #2224
The issue had been caused by a race condition in asynchronous processing.
In `setLastPatchedApp()` method, `await` keyword was needed before `deleteLastPatchedApp();`
```dart
Future<void> deleteLastPatchedApp() async {
final PatchedApplication? app = getLastPatchedApp();
if (app != null) {
print('kitadai31: (2) Starting a 2 seconds wait');
await Future.delayed(const Duration(seconds: 2)); // <- ADDED
print('kitadai31: (5) 2 seconds elapsed. Delete files/lastPatchedApp.apk');
final File file = File(app.patchedFilePath);
await file.delete();
await _prefs.remove('lastPatchedApp');
}
}
Future<void> setLastPatchedApp(PatchedApplication app, File outFile) async {
print('kitadai31: (1) calling deleteLastPatchedApp()');
deleteLastPatchedApp();
final Directory appCache = await …
```
=> fix: Fix cancelling installation by not prematurely deleting patched APK 

app/src/main/java/app/revanced/manager/MainActivity.kt, app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt, app/src/main/java/app/revanced/manager/ui/screen/settings/AboutSettingsScreen.kt
Closes https://github.com/ReVanced/revanced-manager/issues/2499
Side note, these 2 buttons are not very intuitive, they don't seems to be doing anything honestly (regardless of this PR). No confirmation menu is shown, nothing that tells the user that something is being done. 
https://github.com/user-attachments/assets/74fcbf8a-7575-4254-bed6-d4c646189fd4
=> feat(Compose): Move developer options to top level

lib/ui/views/installer/installer_viewmodel.dart
Fix the issue that this error is always thrown when patching failed.
```
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-ESURPI/out.apk' (OS Error: No such file or directory, errno = 2)
```
This was caused by a bug that "Save patched app" attempts to copy the patched APK even if patching failed.
This error was generated regardless of the actual reason why the patch failed, and was adding unnecessary noise to troubleshooting.
Since this PR conflicts with #2332, please merge it first.
After that I will fix the conflict.
=> fix: "Save patched app" attempts to copy APK when patching fails

app/src/main/AndroidManifest.xml, app/src/main/java/app/revanced/manager/util/PM.kt
Implemented https://github.com/ReVanced/revanced-manager/issues/2556 in compose
=> feat: Set app ownership when installing apps

android/app/src/main/AndroidManifest.xml
Part of commit [21ceadaf7f8e7138cf750a47142796208620cb59](https://github.com/ReVanced/revanced-manager/commit/21ceadaf7f8e7138cf750a47142796208620cb59) added option in AndroidManifest.xml to disable use of Impeller rendering backend of Flutter, to fix issues like [mine](https://github.com/ReVanced/revanced-manager/issues/2553).
I tested this in release 1.25.0 and Impeller was still used, causing same crashing as previous version. I found that the option is ineffectual when nested inside another tag, this pull request fixes it.
Move the option to disable Impeller out of the `<activity> ... </activity>` tag block. When nested inside there, the option is ineffectual.
Will close [2553](https://github.com/ReVanced/revanced-manager/issues/2553)
=> fix: Disable Impeller Flutter render engine correctly to fix rendering issues

app/src/main/java/app/revanced/manager/domain/repository/DownloadedAppRepository.kt, app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt
Closes https://github.com/ReVanced/revanced-manager/issues/2578.
=> fix: Allow different app version when downloading via plugin if setting is off

.github/workflows/build_pull_request.yml, .github/workflows/release.yml, .github/workflows/sync_crowdin.yml
Why fetch *all* commit history when we are not going to use them.
=> ci: Remove fetch-depth from checkout

app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt, app/src/main/res/values/strings.xml
Several improvements for the notification which appears while patcher is running.
Changes:
The large icon was unnecessary.
Reason:
- According to the developers document, this icon must not be the app icon.
https://developer.android.com/develop/ui/views/notifications#Templates
- It didn't look good in light mode.
See https://github.com/ReVanced/revanced-manager/issues/2567#issuecomment-2999108092 for a image.
`IMPORTANCE_HIGH` = Status bar icon + Sound + Heads-up banner.
`IMPORTANCE_LOW` = Status bar icon only.
Semantically, this notification is not important as it is merely necessary to run the foreground service.
So the latter is suitable for it.
This resolves the annoyance of a notification sound and Heads-up banner each time you start applying a patch.
(`IMPORTANCE_MIN` cannot be used …
=> fix: Improve background running notification

app/src/main/java/app/revanced/manager/ui/screen/settings/update/UpdatesSettingsScreen.kt
I choosed "Manager" as every settings in that menu relate to the manager. In the future some setting regarding bundle updates may be introduced, which would use a new header "Bundle".
Closes https://github.com/ReVanced/revanced-manager/issues/1966. 
PS: The placeholder for "No downloaded apps" has already been added.
=> fix: Add missing header for "Updates" settings
